#pragma once

#define BI_DEPTHS_TEXTURE 0
#define BI_NORMALS_TEXTURE 1
#define BI_RANDOM_TEXTURE 2
#define BI_SSAO_TEXTURE 3

#define BI_MATRIX_WORLD_PROJ 1
#define BI_MATRIX_VIEW_WORLD 2
#define BI_BLUR_DIRECTION 3