#define BI_VOXELS_GBUFFER_IMAGE 0
#define BI_VOXELS_OCCLUSION_IMAGE 1
#define BI_VOXELS_ILLUMINATION_IMAGE 2

#define BI_DEPTH_TEXTURE 1
#define BI_VOXELS_ILLUMINATION_TEXTURE 2
#define BI_VOXELS_OCCLUSION_TEXTURE 3
#define BI_HEMISPHERE_SAMPLES_TEXTURE 4
#define BI_GATHER_GI_TEXTURE 5

#define BI_ORTHO_MATRICES 0
#define BI_VOXELS_AABB_PMIN 4
#define BI_VOXELS_AABB_PMAX 5
#define BI_MATRIX_WORLD_PROJ 6

#define SAMPLES_SIDE 4
#define RAY_COUNT 1