#pragma once

// textures
#define BI_SKY_CUBEMAP 10
#define BI_SKY_DIFFUSE_CUBEMAP 11
#define BI_SSAO_TEXTURE 12
#define BI_AO_VOLUME 13
#define BI_SDF_VOLUME 14
#define BI_LIGHT_LIST_HEAD 15

// uniforms buffers
#define BI_SCENE_UNIFORMS 1
#define BI_SURFACE_DYNAMIC_UNIFORMS 2

// ssbos
#define BI_EXPOSURE_VALUES_SSBO 4
#define BI_SPHERE_LIGHTS_SSBO 5
#define BI_SPOT_LIGHTS_SSBO 6
#define BI_RECTANGLE_LIGHTS_SSBO 7
#define BI_SUN_LIGHTS_SSBO 8
#define BI_LIGHT_LIST_DATA_SSBO 9
#define BI_HAMMERSLEY_SAMPLES_SSBO 10
#define BI_SKINNING_PALETTE_SSBO 11