#pragma once

// textures
#define BI_SKY_CUBEMAP 10
#define BI_SKY_DIFFUSE_CUBEMAP 11
#define BI_SSAO_TEXTURE 12
#define BI_AO_VOLUME 13

// uniforms buffers
#define BI_SCENE_UNIFORMS 1
#define BI_SURFACE_CONSTANT_UNIFORMS 2
#define BI_SURFACE_DYNAMIC_UNIFORMS 3

// ssbos
#define BI_EXPOSURE_VALUES_SSBO 4
#define BI_LIGHTS_SSBO 5
#define BI_HAMMERSLEY_SAMPLES_SSBO 6
#define BI_SKINNING_PALETTE_SSBO 7