#define BI_VOXELS_IMAGE 0

#define BI_VOXELS_TEXTURE 0
#define BI_DEPTH_TEXTURE 1

#define BI_ORTHO_MATRICES 0
#define BI_VOXELS_AABB_PMIN 4
#define BI_VOXELS_AABB_PMAX 5
#define BI_MATRIX_WORLD_PROJ 6