#pragma once

#define HISTOGRAM_MAX 8.0
#define HISTOGRAM_MIN -8.0
#define HISTOGRAM_SIZE 32
#define THREADS_SIZE_X 8
#define THREADS_SIZE_Y 8
#define GATHER_SIZE_X 4
#define GATHER_SIZE_Y 4
#define TILE_SIZE_X THREADS_SIZE_X*GATHER_SIZE_X
#define TILE_SIZE_Y THREADS_SIZE_Y*GATHER_SIZE_Y